version: 2.1

orbs:
  docker: circleci/docker@2.0.2
  heroku: circleci/heroku@1.2.6


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Initialize venv / Install deps
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
      - run:
          name: Linting
          command: |
            . venv/bin/activate
            flake8

workflows:
  main:
    jobs:
      - build-and-test
      - docker/publish:
          extra_build_args: --build-arg DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY --build-arg SENTRY_DSN=$SENTRY_DSN
          image: $DOCKER_LOGIN/oc-lettings
          tag: '$CIRCLE_SHA1,latest'
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - heroku/deploy-via-git:
          requires:
            - build-and-test
            - docker/publish
          filters:
            branches:
              only: master
